### ISSUE TITLE
TModLoader Servers Under Heavy Load, but only when downloading bigger mods.

### ISSUE THREAD

**Issue by best-games** [blushiemagic/tModLoader#168]
### Description

When I try to download big mods (Calamity, Thorium, etc.) it says the servers are under heavy load. When download something like Cheat Sheet, it downloads fine.

### Steps to Reproduce

1. Download a mod like Calamity or Thorium.

### Expected behavior 

It will say the TModLoader servers are under heavy load.

### Actual behavior

It should be working, smaller mods like Cheat Sheet are.

### Reproduction frequency

100% of the time.

### Versions

tModLoader v9.2.3

### Mods

None yet.

**Comment by Jofairden** [comment]
Thanks for the report. I think we've been aware of the issue for a while, we don't really have an answer to this yet. The problem is bandwidth. The bigger mods eat away most of our bandwidth, and we are very limited on it. The solution is to move to a server with unlimited bandwidth, but this costs money. (and time to transfer the entire system)

**Comment by Chicken-Bones** [comment]
I guess we could throttle it?

**Comment by JavidPack** [comment]
Bandwidth issues have been solved by github integration and incentives.
