### ISSUE TITLE
wishlist: automatically reload mods on exiting mod browser when added / updated

### ISSUE THREAD

**Issue by slippycheeze** [blushiemagic/tModLoader#195]
### Description

When updating a mod through the mod browser, there is a prompt to remind me to reload mods to have the changes take effect.  It also has an option to make it vanish permanently.

It'd be really nice if, instead, it would be possible to tell the system to automatically enable anything downloaded, and perform a mod reload when I exit the browser back to the main menu, so it reloads once after all the downloads.

(Double bonus Internet points if you prompt to enable new mods on download too, but I imagine there is a good reason you don't already do that.)

That's basically what I do by hand anyway, but saves a couple of clicks. :)

### Versions

tModLoader v0.10.0.1

**Comment by Jofairden** [comment]
To add to this suggestion, I'd like this to just be an option under:
Game menu -> Settings -> tModLoader Settings -> [Automatically enable & reload mods when downloaded from the mod browser]

I think the sole reason why this isn't a thing is because it'd be reloading after every single download, so the best option here is to only do it upon leaving the browser menu (back to main menu)
