### ISSUE TITLE
[Request] Unified version

### ISSUE THREAD

**Issue by rayman89** [blushiemagic/tModLoader#209]
Would be possible to make an unified version of tmodloader that serves for both steam and GOG or at least make the same group of devs take care of both versions?

**Comment by JavidPack** [comment]
The reason we don't generate the GoG version is because we don't want to aid piracy. To prevent our tools from aiding piracy, we'd have to somehow generate the patches without generating the exe. This is the reason the GOG version is handled offline, but I think if we made it non-trivial to recover the exe from the build process, we could probably do it. In any case, we may need to consider that the person previously responsible for the GOG version might not come back to the modding scene.

**Comment by chrono1313** [comment]
I purchased the GOG version and paid for many of my friends to get the GOG version. Partially for the no DRM, but also for the lower price and extras it comes with. It appears the tModLoader for GOG may be abandoned. I have spent the last two days trying to get it to work to no avail. Some not insignificant percentage of tModLoader users are effectively locked out as of now.

**Comment by Chicken-Bones** [comment]
Leaving this open because we should be able to make a patcher when we have time

**Comment by rayman89** [comment]
Are there any news on the progress of the unified version or something similar?

**Comment by JavidPack** [comment]
Not much. One of us have purchased the GOG version but no other progress yet.

**Comment by Chicken-Bones** [comment]
https://github.com/blushiemagic/tModLoader/commit/e448b480e4d2abd5a7aa153b2360d6c7f8200c1d
