### ISSUE TITLE
GlobalItem data is lost when player uses Quick Stack (for unstackable items) to a chest (containing any such item) in multiplayer

### ISSUE THREAD

**Issue by hamstar0** [blushiemagic/tModLoader#235]
### Description

See title.

### Steps to Reproduce

See title.

### Expected behavior 

Not what title says.

### Actual behavior

What title says.

### Reproduction frequency

100% during a locally-hosted test.

### Versions

v0.10.0.2 tModLoader

### Mods

Durability (relevant), Dynamic Invasions (relevant), Hamstar's Helpers

### Additional Information

Relevant source files:
https://github.com/hamstar0/tml-dynamicinvasions-mod/blob/master/Items/AggregatorItemInfo.cs
https://github.com/hamstar0/tml-durability-mod/blob/master/DurabilityItemInfo.cs

Video proof:
https://forums.terraria.org/index.php?threads/durability.52036/page-4#post-1434072

**Comment by Jofairden** [comment]
Marking file locations for future reference:
Player.cs : 18024 : QuickStackAllChests()
Chest.cs : 180 PutItemInNearbyChest() -- There is an IstheSameAs() check on 199, adding to stack, otherwise .Clone() on 230 (not in chest, empty slot available)

Related MessageIDs: (multiplayer)
5 : SyncEquipment
85 : QuickStackChests

Related array: player.inventoryChestStack

This needs a close look at so it will work properly in multiplayer.

**Comment by Jofairden** [comment]
To be handled: #265
