### ISSUE TITLE
World Creation

### ISSUE THREAD

**Issue by lawura** [blushiemagic/tModLoader#244]
Prerequisites
### Description
iModLoader prevents choice of corruption type of the world upon world creation.

### Expected behavior 
Original current version of Terraria allows choice of corruption type in the  world (crimson/corruption)

### Actual behavior
Choice in world creation does not appear.

### Reproduction frequency
continuous

### Versions
Terraria  3.5.2
Win tModLoader 0.10.0.2

### Mods
Unmoded

**Comment by JavidPack** [comment]
You probably just never got to Hardmode while playing tModLoader . Since tModLoader has it's own saves directory separate from vanilla saves, it wouldn't know if you have unlocked this privileged. You can edit "Documents\My Games\Terraria\ModLoader\config.json" and edit the "SettingsUnlock_WorldEvil" setting to be true, save it, then launch tModLoader .
