### ISSUE TITLE
Placing something like ExampleChest makes a dirt block.

### ISSUE THREAD

**Issue by MacindowsRegistry** [blushiemagic/tModLoader#274]
### Description

When making a placeable block (such as a chest or block) it only place's a dirt block. Is this an ID or block error?

### Steps to Reproduce

1. Make the item/block
2. Place it
3. Dirt Block.

### Expected behavior 

To place chest / block

### Actual behavior

Placed a dirt block.

### Reproduction frequency

Infinity

### Versions

`tModLoader v0.10.1` `tModLoader v0.10.2`

### Mods

Extra Items (By me)

**Comment by JavidPack** [comment]
You have a spelling mistake. Rather than using the mod.TileType("tilename") way, using mod.TileType<tileclassname>() way will catch these mistakes while building instead of silently fail in-game.

Remember, this is NOT where you get support for making mods, this issue tracker is only for actual bugs in tModLoader. Come to http://discord.me/tmodloader for modding help.

**Comment by MacindowsRegistry** [comment]
ok
