### ISSUE TITLE
Error building mod (dll error)

### ISSUE THREAD

**Issue by ronitrocket** [blushiemagic/tModLoader#276]
### Description
I am using a Macbook Pro Sierra.

I am trying to build my mod, but I get an error message related to DLL files apparently:

Missing dll files for RonitrocketsMod

Must have either All.dll or both of Windows.dll and Mono.dll
All.dll must not have any references to Microsoft.Xna.Framework or FNA
Windows.dll must reference the windows Terraria.exe and Microsoft.Xna.Framework.dll
Mono.dll must reference a non-windows Terraria.exe and FNA.dll

### Steps to Reproduce

1. I first used the mod skeleton to make a simple mod with one sword.
2. Building it the first time a different error message came up, which I fixed with noCompile = true
3. After that I began getting the message above.

### Expected behavior 

Following Jofairden's tutorial, (the first one) it explained that the mod should build, however I got the first error message, which I fixed, and now I got this one.

### Reproduction frequency

This is my first mod so I can't say

### Versions

tModLoader v0.10.1

### Mods

No mods were active

Thanks for your help.

**Comment by JavidPack** [comment]
I don't know what tutorial you are talking about, but since you didn't mention which IDE you are using, I'm guessing you aren't actually building the dll files you need.

That said, remember, this is NOT where you get support for making mods, this issue tracker is only for actual bugs in tModLoader. Come to http://discord.me/tmodloader for modding help.
