### ISSUE TITLE
Rare server autosave error with foreach and tile entities.

### ISSUE THREAD

**Issue by JavidPack** [blushiemagic/tModLoader#279]
Via misario:
![](https://i.imgur.com/5yHpOsf.png)
can easily be fixed by saving keys to an array here and using for instead
![](https://media.discordapp.net/attachments/386331804770107414/387402319962177538/unknown.png?width=400&height=142)

**Comment by Chicken-Bones** [comment]
Unfortunately saving the keys to an array will also cause a concurrent modification exception.
After looking very briefly through the threaded save and play callback, I'm calling out a fundamental threading architecture problem. The world can be modified (in any way) mid-save, which **can** cause the loaded file to be inconsistent (regardless of runtime crashes). The takehome is always call save and shutdown your sever properly, because actually fixing this is beyond our scope.

The naive stopgap solution is to just lock on all modifications to the dictonary, however there may be too many places in the code that maintenance and slowdown becomes annoying, 

A better solution is to snapshot the tile-entity and other dictionaries on the main thread and store them in temp variables before the save call is invoked on the threadpool.

I'll note that there are other locations which could have the same issue, `SaveWeightedPressurePlates` `SaveTownManager` etc but vanilla gets away with these (and tile entities) because they're so rarely modified that the chances of them colliding with the save loop is very low.

There are many locations for small inconsistencies in save files to appear in other parts that won't throw an exception as well. For example, in several locations, an npc is set to active = true, before being assigned all its valid data, so it could end up getting saved in the middle of this process, causing an invalid npc to be spawned on load. Vanilla tends to be written (especially old code) in such a way that it makes very few assumptions about the state of the fields of its objects. If an entity is saved with a location, or id, or data, or something else that's 'corrupted' it generally just spazzes out or despawns.

Of course, vanilla also gets away with this for the most part because loading a world from autosave rarely happens unless the game crashes or is forcibly closed, and then it has the backup so that if an exception is raised during loading it can use the previous save.

All these measures mean that the chances of a world being irreparably damaged are very low indeed, but not zero, and things like mods using more entities and tile entities only increases the chances of encountering these flaws.

**Comment by Jofairden** [comment]
Can't we make the dictionary a volatile?

**Comment by Chicken-Bones** [comment]
That's not how volatile works, however ConcurrentDictionary would probably work

**Comment by Jofairden** [comment]
Yes, it looks like ConcurrentDictionary will fix it. Is there a way to force trigger this error?

**Comment by Chicken-Bones** [comment]
Actually on consideration, you could just toss a massive try catch around the autosave, and if it fails, well, probably won't fail next time :')
