### ISSUE TITLE
Invisible enemies in multiplayer

### ISSUE THREAD

**Issue by Mourdraug** [blushiemagic/tModLoader#295]
### Description

I'm playing on Calamity+Tremor+Thorium server (server running in my Lan on separate machine) with my friend and noticed that sometimes when we hit a mob it disappears for client, but ranged ones will still shoot projectiles. 
We noticed this AFTER Devourer of Gods during Pumpkin Moon, Frost Moon and Solar Eclipse. It generally looks like this: Mob spawns, we hit the mob, with damage that should not kill it, but there is sound of it dying and it disappears. But if it's ranged it will continue to shoot at us.
But wait! There is more. This problem persists in full form only when we're both online. If there is only one player online, mobs also disappear, but reappear shortly after.

### Steps to Reproduce

1. Start server with Calamity, Tremor and Thorium (possibly will still work with Calamity alone)
2. Kill Devourer of Gods from Calamity
3. Start Frost Moon with 2 clients connected
4. Locate Elf Copter and hit it for approx 2000 dmg

### Expected behavior 

Elf copter should still be alive, kicking and visible since it should have more than 2k max hp at that point.

### Actual behavior

I'm guessing that some event enemies have buffed health after certain post moon lord bosses get killed. It seems to me that there is some kind of desync in health value between client's and server as to what actual value should be, and as a result enemies die on client side but still live and shoot on servers side. What puzzles me the most is the fact that with only one client online it seems to resync shortly after. 

### Reproduction frequency

Happens during every event and effects are visible on both clients.

### Versions

0.10.1.1

### Mods

1. Calamity
2. Tremor
3. Thorium

**Comment by JavidPack** [comment]
Is there anyway you can narrow this down to just 1 mod, and then inform the developers of that mod that they have bugs? I agree with your assessment of the cause of the error, but the problem lies with those mods not properly syncing their ModWorld variables, not with tModLoader, as far as I can tell.

**Comment by Mourdraug** [comment]
I'm not entirely sure if it's simply a problem with one of the mods, I'll test it more extensively when I'll have a moment. It might also be problem with interaction between mods, I believe that both Tremor and Calamity alter enemies statistics, which could lead to nondeterministic and as a result incorrectly synced values if mod loader doesn't resolve it by some kind of static order. I'm not really familiar with how tmodloader handles this (because I never developed any terraria mod), nor how these mods implement stat change so that's just a guess on my part. I'll see if I can replicate this with only one of these mods.

**Comment by JavidPack** [comment]
Reopen if you narrow it down to a tModLoader problem or shortcoming.

**Comment by WeebNeet** [comment]
If it hasnt been narrowed down to the tModloader, I can say it has to do something with the Calamity Mod, as I experienced the exacct same problem with a friend. In any given Event: All Mini-Bosses or enemies with a large HP-Pool just disappear for some reason.
I am playing with my friend as I am writing this and all of the sudden, after ~5 minutes or something, all enemies that disappeared suddenly reappeard and were attackable again and no enemies disappear anymore. I was tabbed out the whole time and I will just briefly describe what was happening right now:
I was tabbed out and my friend was just staying next to me.
No enemies were near us EXCEPT the invisble ones (Because they ARE there, just Invisible and Invincible)
A few seconds after he teleported himself back to base, all the enemies reappeared and everything was normal again (We were able to attack freshly spawned enemies, mainly the Mothron, without them just disappearing)
