### ISSUE TITLE
Skip Loading Mods option for Loading Error window

### ISSUE THREAD

**Issue by JavidPack** [blushiemagic/tModLoader#303]
Some mods crash the loading process at a point where tModLoader is unable to to detect which mod is the culprit, throwing tModLoader into a reload loop. Currently we have 2 buttons on the Loading Error Window, Continue and Open Logs folder. (and sometimes Open Web Help)

I suggest adding an additional button to skip the reload. Currently we can skip loading mods by holding shift, but that isn't common knowledge. This button might be named "Cancel" or "Don't Reload Mods"

**Comment by JavidPack** [comment]
[ThrowingClass.zip](https://github.com/blushiemagic/tModLoader/files/1755934/ThrowingClass.zip)

Attached is a Mod that causes the reload loop.

**Comment by Chicken-Bones** [comment]
This particular reload loop is caused by incorrect attribution of the mod at fault, because a `GlobalItem` throws an exception during `SetDefaults` in `ModLoaderMod`

This class of errors can be caught and correctly attributed by examining the stack trace finding the first method inside a mod assembly. 

I'll add the catch after the button is added. The button will just be the continue button but disabling all mods before continuing.

**Comment by JavidPack** [comment]
Is this still relevant with the new loading loop we have now? I can add more buttons to the UIState if so.

**Comment by Chicken-Bones** [comment]
This is still relevant. I have not implemented 'first mod at fault' yet
