### ISSUE TITLE
Damage types and custom support

### ISSUE THREAD

**Issue by orian34** [blushiemagic/tModLoader#311]
Here's is a small suggestion, that might already have been looked at, but anyways

It is about having some kind of array with all damage type.
Creating a list containing all the damage types, and modders could add their own custom damage type in the list.
Then, someone who wants to increases all damage types can just use the tml list, that will automatically include the supported mod damage types.
A bit like how Boss checklist allows boss support from mods, but having access the the checklist as a whole to add to modded damage types in your effect, without needing to reference each of them one by one, because they would be supported in the list already.

**Comment by Jofairden** [comment]
I think we've specifically chosen to not provide internal support for modded damage types on a global level since vanilla doesn't really provide any structure for it. It's already possible to create a new damage type either way, as well as modifying damage values from other mods, provided that they've opened up their code to do so. ExampleMod already has an example damage type, how it could be done properly. If the other modder opens up their damage classes, other mods could modify the values.

**Comment by orian34** [comment]
All gucci then! Thanks for the answer
