### ISSUE TITLE
Mod Class Request: ModEvent

### ISSUE THREAD

**Issue by Agrair** [blushiemagic/tModLoader#404]
### What is it?
There are many base classes in tModLoader to be extended from, but there is one that remains nonexistent, and one I have been trying to create for a while.

### Description
Something I have been trying to replicate for a while is an invasion type event, such as the *Goblin Invasion*, or the *Pirates*.  However, there is no `ModEvent` base class for modders to take advantage of.  Of course, I could do everything manually, but something that automatically creates the progression bar and keeps track of *points*, as they're called in the *Pumpkin Moon*, would greatly be appreciated.

**Comment by Chicken-Bones** [comment]
Would you be so kind as to design an implementation as a starting point and submit a pull request? The dev team is quite undermanned at the current time, but we're happy to help other deva get involved. Give us a ping on Discord if you need assistance setting up

**Comment by Agrair** [comment]
Of course, however, I seem to be having difficulty with the tModLoader src, so expect that pull request rather far into the future.

**Comment by Jofairden** [comment]
I once attempted creating a ModEvent class. I managed to mess up somewhere and couldn't find it so eventually I just threw that away so unfortunately I have no base you could work with. I'm just trying to say the vanilla event code is code that will make you less sane, lol.

**Comment by Agrair** [comment]
Another Modder showed me his code for an event, and he seems to have used GlobalNPC and ModWorld, but what I was really looking for was the UI. Maybe it would be easier to use three different classes?

**Comment by Agrair** [comment]
But he said that it was from the original Terraria Frost Moon.

**Comment by Jofairden** [comment]
The problem is that lots of event based stuff in Terraria is hardcoded. When you design a ModEvent system ideally you make it dynamic in such way that allows modders to create new ModEvents at will, and have them automatically handled in tML's system. That is the hard part, because quite a few places need changes for that. On top of that the DD3 crossover event was implemented differently, making things even more confusing. It is already possible to make something event-like as you stated with certain existing classes, but it is nowhere near a beautiful implementation.
