### ISSUE TITLE
Interpolation

### ISSUE THREAD

**Issue by Agrair** [blushiemagic/tModLoader#411]
This is in fact something I am attempting to learn how to create on my own, but if I could get advice from experience coders, that would be great. What I’m trying to do is create a way blend two or more sprites/frames together to look like they are smooth frames to save many from the costs of spriting. Of course, this will not apply for everything right now, but what I’m really looking for is feedback.

**Comment by Agrair** [comment]
Or any kinds of suggestions on how to implement this

**Comment by JavidPack** [comment]
This isn't really a question suitable for github issues, more for discord.

That said, I'll answer.

Rotating the sprite is simple, if that is the motion you are trying to interpolate.

Otherwise, you can try manually drawing. Cross fading between 2 separate sprites just by drawing A at a transparency and B at 1-transparency on top of each other could work. There might be some BlendState considerations that someone doing this might need to think of.

In any case, interpolating like this probably won't end up looking good because of the pixel art style.

**Comment by Agrair** [comment]
Well what I’m really want to do is make it look like there is growth between two frames, but I want it to be minuscule like a plant irl.
