### ISSUE TITLE
UI clicking failure

### ISSUE THREAD

**Issue by Agrair** [blushiemagic/tModLoader#459]
### Description

When I try to edit a keybind, everything stops working and I have to click on another program that's running, then click back on Terraria every time.

### Steps to Reproduce

1. Go to the Keybinds part of Settings
2. Click anything

### Expected behavior 

I should be able to edit a keybind.

### Actual behavior

All the UI won't click, all the hovering works but not the buttons themselves.

### Reproduction frequency

Without mods.

### Versions

I'm currently using a GitHub version, but I've been having some problems building so this is prolly just normal 0.10.15.

### Additional Information

I'm pretty sure this is happening for all Settings UI.
Also, I'm trying to do this for VeinMiner since I don't have the whitelisting key.

**Comment by Agrair** [comment]
Also, I can edit keybinds now but I have to manually check input_profiles.json.

**Comment by JavidPack** [comment]
You'll need to give more information, since it works for everyone else.

I've seen issues like this with Bitdefender preventing games from editing files in the My Documents folder, maybe that's related to this.

**Comment by Agrair** [comment]
Actually, it turns out it's just the Main Menu.

**Comment by Agrair** [comment]
It works in game.

**Comment by Agrair** [comment]
Yes, it seemed to be some kind of problem where Terraria could not access my player reference (or something like that) and couldn’t set my new hotkeys.

**Comment by JavidPack** [comment]
If you could help us replicate, that would be nice. I'm pretty sure a Player reference isn't involved in the hotkey interface. Details like enabled mods, config.json and input profiles.json that would replicate the problem would help us figure this out.

Also, explain why you think the problem is "Terraria could not access my player reference". Are you assuming? did you see an error message?
