### ISSUE TITLE
Add Ore Generation after an Event

### ISSUE THREAD

**Issue by Melone01** [blushiemagic/tModLoader#463]
Would be pretty helpful if you added some Code on Ore Generation after defeating a Boss or so in ExampleMod. It could be useful for People trying to make a bigger Mod.

**Comment by Jofairden** [comment]
Thanks for the suggestion, however there are already examples of ore generation _and_ code to execute when a mob is defeated. These can be combined by a modder to reach the desired purpose or goal. 

Thanks again for the suggestion, however I would like to clarify that github 'issues' such as these are solely meant for bugs/problems in tML, or suggestions such as new hooks or changes to existing ones. I just wanted to clarify so it doesn't seem like the issue is closed out of nowhere. (since I feel like example mod already covers this, you just need to know where to look. And yes, that's the biggest problem with example mod right now)
