### ISSUE TITLE
Add piracy checking

### ISSUE THREAD

**Issue by Shimogawa** [blushiemagic/tModLoader#482]
### Description

It is believed that tML needs Steam to run, but recently I found that a modified `steam_api.dll` can be used to bypass the Steam check. Many players here do not want to pay for the game, so they use a pirate version of Terraria, and also tML if replacing the executable. Thus, I think a check on `steam_api.dll` should be performed.

### Versions

All versions.

### Additional Information

I suggest to perform a SHA1 or any other Hash check on the library before running `SocialAPI` to check the integrity of official version of tML including any other libraries it uses. 

The SHA1 hash of vanilla `steam_api.dll` is `4ee43374520904fa6d80c12c273d67eb7b5c984e`. I wrote my own solution as follows:
```cs
byte[] b = new byte[] { 0x4e, 0xe4, 0x33, 0x74, 0x52, 0x09, 0x04, 0xfa, 0x6d, 0x80, 0xc1, 0x2c, 0x27, 0x3d, 0x67, 0xeb, 0x7b, 0x5c, 0x98, 0x4e };
var data = File.ReadAllBytes("steam_api.dll");
var hash = SHA1.Create().ComputeHash(data);
if (hash.SequenceEqual(b)) {...}    // using System.Linq
```

~~Also, the pirate version of `steam_api.dll` can be downloaded here: [modified_steam_api.zip]~~

**Comment by Chicken-Bones** [comment]
See, you're missing the part where anyone can modify and build tModLoader to remove the check.

**Comment by Shimogawa** [comment]
Not everyone knows how to modify the client, and also modifying the dll is currently the only variant of piracy as far as I know. Also, I think adding this checker can at least block most of the users who use pirate version and also the piracy problem in China is so severe that we should take action.

**Comment by Chicken-Bones** [comment]
Yeah but it only takes one person to modify it and release it. It's just like steam_api.dll but /easier/. Also tModLoader is small in comparison to Terraria.

**Comment by Dierney** [comment]
To be honest, because of Chinese government, Chinese players do not have access to the websites outside China. We (SBMW Group), as the biggest mod localization and transferring group in China, are the administrator in the Chinese Terraria community. We really want to improve the game environment so that the severity of piracy can diminish, and we are providing the mods only to Steam and GOG players. 

If you feel it is not necessary, please give us the permission to add the checking code to the tML distribution to Chinese players by our own.

**Comment by Chicken-Bones** [comment]
Ah, so, in light of that additional revelation, we could add it. I'll see what the other devs think.

As for permission, it's gladly granted, but you didn't need it. TML is open source and freely redistributable (to anyone who owns the game legally). Anyone can modify it, we'd just appreciate if people who make significant (not you) modifications don't claim to be official representatives and keep their modifications public

**Comment by Dierney** [comment]
Thank you very much!

**Comment by Luiafk** [comment]
I don't understand this at all tbh, if the developers of the game are fine with zero drm (gog) why would you want to add your own, there's no benefit to tmodloader, and it's something the developers could add themselves if they actually wanted it?

`and we are providing the mods only to Steam and GOG players.`
This would stop gog players from even being able to use it, people that have paid the developers for the game.

**Comment by Jofairden** [comment]
@Luiafk tModLoader is not released for GoG but only Steam, and Terraria requires Steam to actually play the game (as per most/all Steam releases). The current situation in context is pirates using a modified steam wrapper to bypass steam checks, which allows them to play the game without having purchased it on Steam.

**Comment by Luiafk** [comment]
`The current situation in context is pirates using a modified steam wrapper to bypass steam checks, which allows them to play the game without having purchased it on Steam.`
They do this with the vanilla version, which the developers are either fine with or do nothing about it. Why a third party would want to do something about it I don't know.

`You misunderstand, this is a Steam situation that happens for Steam users only (which happens to be the only platform tML is released for as of yet)`
I didn't misunderstand anything, Dierney said his company gives the files to people who have the game through GoG, this would stop those players from being able to play.

**Comment by Jofairden** [comment]
> I didn't misunderstand anything, Dierney said his company gives the files to people who have the game through GoG, this would stop those players from being able to play.
No, you misunderstand again. **This is a check than runs for Steam players, not GoG players**. Read my message again

**Comment by Shimogawa** [comment]
Well actually I did not see anyone uses GoG in China so I'm sure if they are using Steam distribution of Terraria this dll must exist.

**Comment by Shimogawa** [comment]
Also if you look into the source code of terraria there is only Steam apis. I actually don't know if GoG has Terraria at all.

**Comment by zauberparacelsus** [comment]
> Also if you look into the source code of terraria there are only Steam apis. I actually don't know if GoG has Terraria at all.

It's on there:  https://www.gog.com/game/terraria

**Comment by Luiafk** [comment]
Unless Dierney's giving out tmod 1.3.4.4 for gog (which seems pointless since all the mods are outdated) then it affects people with the gog version of the game. I assumed he's giving gog players the steam version with the cracked dll, but who knows :woman_shrugging:.

Regardless, it's dumb either way. If ReLogic wanted more drm they wouldn't have a GoG version of the game, and they'd use more than the default Steam drm. If they're fine with the level of drm currently I don't see why anyone else would want to add more.

GoG has Terraria, yes.

**Comment by Luiafk** [comment]
And ignoring Dierney and whether he gives out the gog version or not, there's no reason why people that have bought the game on gog shouldn't be able to use tmodloader.

**Comment by Shimogawa** [comment]
Does tmodloader has a GoG version? Just asking cuz I don't know.

**Comment by Luiafk** [comment]
Someone used to make a patcher for the gog version, he disappeared though, so it hasn't been updated since 1.3.4.4 terraria

**Comment by Shimogawa** [comment]
Well now you have a good point. It is unreasonable for GoG players to have a piracy check on Steam library. Maybe it needs more considerations on whether tmodloader does offer service to gog players.

**Comment by Dierney** [comment]
I'm so sorry I didn't make myself clear. We transfer a large number of mods to all Chinese players. But we are providing the own localized mods only to anyone who owns the game legally. As for "and GoG players", was me gilded the lily. our transmission of mods and tModLoader has exceeded 200,000 downloads, but never found any GoG players. And tModLoader doesn't seem to have gave out any GoG version. I believe there will be a better solution if the GoG version is gave out, but not yet.

**Comment by Shimogawa** [comment]
Checking the platform is easy. It is only a case of `Platform.IsWindows`. Also, I don't think currently Terraria is a 64-bit program, as in vanilla it comes with the 32-bit steam_api.dll. If next version tml supports 64 bit machine, this is a problem.
I know that this is a minor fix, or even sounds nonsence, but adding these few lines of code may help us a lot and also helps a little combating pirates. As always, we hope that this function could be added, but if this is not applicable, we are also happy to accept because you have your own consideration.

**Comment by Chicken-Bones** [comment]
Ideally we want to support GoG, but only for players who bought the game through this means. We were planning on distributing a patcher to produce the GoG version in a similar fashion but haven't had the time/priority.

Unfortunately preventing redistribution of modified versions is impossible, but it doesn't mean there's no reason to do something which might discourage just a bit of piracy.

**Comment by Chicken-Bones** [comment]
Accidental close. I don't follow all the discussion here, but it doesn't take much effort to add a windows steam dll check, and if that will help Chinese distribution then why not

**Comment by kres0345** [comment]
This seems unnecessary and irrelevant

1. We are not the ones to make sure that the install isn't pirated
2. Just as the above one, tModLoader is not a DRM, making it a DRM could discourage mod developers. to use it

Even though this is suggested with a kind heart, it might result in worse. It could be a stepping stone to making players buy the game of off a black market key resellers, G2A and alike, and would be, IMO, worse than pirating the game.

Another scenario would be that an alternative to tModLoader is made, to combat the DRM opinion. That would split the modding community and make it tiresome or impossible for players to dual-wield 2 mods from different modding frameworks.

**Comment by Ristovski** [comment]
You are talking about adding another check to Terraria to battle piracy and then yourself provide a "modified" `steam_api.dll`. 

Also, how would this work on Linux/Mac? They use native versions of `steam_api.so` and not the Windows dlls.

If you were to implement the check with a basic md5sum "integrity" check I can assure you that can be cracked with a single `sed` command under Linux by directly replacing the md5sum with the one from the "modified" `steam_api.{so,dll}`.

Which means you would have to actually put effort into creating a non-trivial DRM.

**Is tModLoader supposed to be a DRM? No.**

**Comment by Chicken-Bones** [comment]
Done https://github.com/blushiemagic/tModLoader/commit/c6f5136ce53e818375e416eda61c7c2cda866ecd

@Ristovski nothing you've said is wrong, but I'll quote my last comment and say "it doesn't take much effort to add a windows steam dll check, and if that will help Chinese distribution then why not"
Yes it's easy to circumvent, and no we won't participate in an escalating drm war, but this cost me 10 minutes.

**Comment by hamza20150** [comment]
guys i have cracked terraria and i like to play with too many mods and i need to dawnload tmodlaoder 64 bit cuz everytime i want to play .  the game crash.
and i dawnload the tmodloader 64 bit but when i start the game it tell me to buy the game but let me tell you something in my country its illegal to have credit card and i cant buy the game . . . 
i hate my selfe to to play cracked game but what i have to do so guys please help to fix terraria or too write a code to tmodloader 64 bit too play without steam account or to buy the game 
and soory guys my english is very bad  . . . . .

**Comment by IshakPlayz800** [comment]
i actually have no idea why the fuck would you want to add piracy checking ??

**Comment by cgarz** [comment]
Are there any tModLoader alternatives or at least forks of tModLoader that don't have disgusting DRM yet? Like @kres0345 suggested would happen?

I thought DRM was universally hated. I wonder if money changed hands or something.
The fact that a mod could implement DRM, where the base game apparently deliberately does not, just blows my mind. In a bad way.

**Comment by kres0345** [comment]
Furthermore, the fact that Re-Logic chose to release the game on GOG as well as steam, emphasize that the developers (and/or publishers) aren't interested in DRMs

**Comment by cgarz** [comment]
Well that confirms my fears.

Thank you tModLoader. For actually going as far as deleting posts linking to the official Terraria forums about this. Even despite the post actually being out of date, and no longer being maintained, since GoG is now supported.

Your true colors have been shown.

Hopefully someone makes a better one free from this ones self righteousness and other issues.

**Comment by Jofairden** [comment]
> where the base game apparently deliberately does not
@cgarz 

Not trying to be rude, but the Steam version of Terraria simply has the Steam DRM embedded in it. That's how it works for Steam games. If you actually paid attention, the check implemented simply checks if the steam file is the correct file, and not a pirated one. The check is disabled for GoG version, which you can verify right here: https://github.com/tModLoader/tModLoader/commit/c6f5136ce53e818375e416eda61c7c2cda866ecd#diff-dda0bda3579581f7ddcb49cafa199cceR38

We don't condone piracy, we never have. The steam version of TML simply checks if the steam file is correct. If you've been using (Steam) TML up to this point, you've always been playing TML with DRM in it, with or without the implemented check.

**Comment by Chicken-Bones** [comment]
> Thank you tModLoader. For actually going as far as deleting posts linking to the official Terraria forums about this. Even despite the post actually being out of date, and no longer being maintained, since GoG is now supported.

I apologise, I didn't read it in enough detail before deleting it. It the post _was_ a way to remove the current steam/gog verification, I'd have to censor it.

GoG is DRM free, tML just checks you have a valid copy of GoG Terraria. We require you to own the game.

**Comment by kres0345** [comment]
I stand corrected, the lack of GoG verification was simply speculation due to it not being mentioned previously in this thread. (I don't condone the deletion of my comment, have no idea way)

I am still confused as to what the "patch" was for if it wasn't for fixing the DRM check on GoG version

**Comment by cgarz** [comment]
> the Steam version of Terraria simply has the Steam DRM embedded in it.
@Jofairden

No it doesn't. If you mean the Steamworks API then that's not a DRM. That's an API.

If steamworks is DRM then .NET is DRM.
Wine and Mono work just fine to emulate .NET and other Windows things.
Does that mean that using Wine to run programs meant for Windows on another OS by emulating their API is piracy? **Of course not.**

Steam's API can be emulated by other programs, such as the open source Goldberg emulator.
Exactly like how Wine and Mono can emulate Windows APIs.

Steam has **actual** DRM systems such as Steam stub or CEG. They are easy for developers to add.
But did Re-Logic choose to flip a switch and have these intrusive things implemented? **No**.

> If you actually paid attention, the check implemented simply checks if the steam file is the correct file, and not a pirated one.

Yes, that's what a DRM is. It is forcing you to use the steamworks API, just like what steam stub would do.

> The check is disabled for GoG version

Forcing use of the steam API is disabled yes. But the GoG Terraria.exe is verified instead.
Which is absolutely pointless in the pursuit of thwarting piracy. If you were to pirate the GoG Terraria you would receive the unmodified Terraria.exe.
There is no DRM on GoG. So there is no need for pirates to patch the Terraria executable.
So why on earth is this even being enforced???

All this does is the same thing DRM has always done. Penalize paying customers.
Now if someone buys GoG's Terraria and wishes to patch the executable for whatever reason, they are locked out of tML. Wonderful.
Meanwhile, the pirates can happily use tML to their hearts content.
 
>The steam version of TML simply checks if the steam file is correct. If you've been using (Steam) TML up to this point, you've always been playing TML with DRM in it, with or without the implemented check.

As you might imagine. My Terraria version is the GoG version. I even stripped the tML installation down to the bare minimum.

> We don't condone piracy, we never have.

How nice. But in your single-minded self-righteousness you have forced DRM into the ecosystem of a game that has clearly chosen to be DRM free.
As well as penalize paying customers for doing what they want with the game they bought.

**Comment by cgarz** [comment]
> I apologise, I didn't read it in enough detail before deleting it. It the post _was_ a way to remove the current steam/gog verification, I'd have to censor it.
@Chicken-Bones 

If this is the case, should you not restore the comment? Can that be done?

**Comment by cgarz** [comment]
> I am still confused as to what the "patch" was for if it wasn't for fixing the DRM check on GoG version
@kres0345 

I'm not 100% sure but I think it was just to add GoG support to the then latest tML.

What it most definitely WASN'T though was DRM circumvention. A simple date comparison shows the post date was Apr 20, 2019. The DRM nonsense was added on Jun 1, 2019.

So your post most certainly should not have been deleted.
However CB has since apologised and if possible perhaps it may be restored soon.

**Comment by Jofairden** [comment]
> 
> 
> > the Steam version of Terraria simply has the Steam DRM embedded in it.
> > @Jofairden
> 
> No it doesn't. If you mean the Steamworks API then that's not a DRM. That's an API.
> 
> If steamworks is DRM then .NET is DRM.
> Wine and Mono work just fine to emulate .NET and other Windows things.
> Does that mean that using Wine to run programs meant for Windows on another OS by emulating their API is piracy? **Of course not.**

You raise a lot of valid points, however it definitely is a DRM: (DRM is more than just anti-piracy stuff)
`The Steam DRM wrapper is an important part of Steam platform because it verifies game ownership and ensures that Steamworks features work properly by launching Steam before launching the game. The Steam DRM wrapper by itself is not is not a anti-piracy solution. The Steam DRM wrapper protects against extremely casual piracy (i.e. copying all game files to another computer) and has some obfuscation, but it is easily removed by a motivated attacker.` Taken straight from their documentation, first hit. You're right however that they're not using it as anti-piracy and you raise some valid points for patching (what are people patching it for though?) Can you give some patching examples? I'll forward this discussion internally

(As for the post, deleted comments cannot be restored it seems)

**Comment by Chicken-Bones** [comment]
Sorry, I tried to restore the deleted comment but I couldn't. I won't argue DRM at length here, I'll avoid using the word.

People who purchase the game through Steam, have their ownership/purchase verified by Steam on each launch. We believe making this [slightly] harder to circumvent was a good move, as reasoned above on this thread. 

If the changes we've made to tML are causing someone to be unable to patch their vanilla game side by side, we're happy to work to resolve that issue.

**Comment by cgarz** [comment]
> You raise a lot of valid points, however it definitely is a DRM: (DRM is more than just anti-piracy stuff)
> `The Steam DRM wrapper is an[...]` Taken straight from their documentation
@Jofairden

I'm not sure but that looks like something like steam stub or similar. Looks like it is to ensure that steam works is running. It applies obfuscation and what not.

If you can just emulate Steam API and the game runs fine then I'd say it's not a DRM.
However, after some searching, I saw that even tools that are for removing other steam DRM systems mention the steam API as DRM sometimes. So I'll accept there is confusion.

> you raise some valid points for patching (what are people patching it for though?) Can you give some patching examples?

Off the top of my head, I'm not sure. Perhaps changing the embedded icon or something.
But the point is not about examples. Its about user freedom.

Just because the DRM pusher can't think of any valid reasons a user might be negatively impacted, does not mean the DRM addition is validated.

I'm sure EA said to themselves, "No one would want more than 1 player per install" when they crippled Spore.

The biggest point with the GoG checksumming though—It does **nothing at all to prevent GoG piracy**.
Paying customers and pirates alike receive the valid executable. Checking it's the right one is just silly.

**Comment by Ristovski** [comment]
> The biggest point with the GoG checksumming though—It does **nothing at all to prevent GoG piracy**.
> Paying customers and pirates alike receive the valid executable. Checking it's the right one is just silly.
@cgarz 

I agree with this. I don't get the point for the GoG check. It does not prevent piracy in any way, it just makes it impossible to edit the Terraria executable.

**Comment by Jofairden** [comment]
> If you can just emulate Steam API and the game runs fine then I'd say it's not a DRM.
However, after some searching, I saw that even tools that are for removing other steam DRM systems mention the steam API as DRM sometimes. So I'll accept there is confusion.

Steam itself calls it their "Steam DRM", enough said. I don't think there is confusion on my end. I think you are simply mistaken in thinking DRM's purpose is _always_ for anti piracy specifically, which isn't always the case. I also think you are coming from the perspective that DRM is always bad, which also isn't always the case. Steam definitely adds their DRM in the form of checking you own the game. Try launching a Steam game without Steam.

When people asked for us to add anti piracy measures, we did. We didn't do it to be annoying, we had a lot of people come in and ask questions why things wouldn't work, why did they get this error etc. All of those issues always arose from pirated versions of the game. A lot of time has been wasted helping people with pirated versions. Let it be clear that we never intended to endorse or promote piracy, we don't support it. We also feel like our addition to the game shouldn't just freely work on pirated versions, because we support the game/Re-Logic.

I don't think there's an argument that regular players are penalized, because how exactly are they penalized? You can still patch the game with further modifications (no idea who's doing this), if you plan on doing so with the standalone GoG version you could simply rename the exe (eg. Terraria_Patched.exe) and it should still work. Then again I know of nobody doing this, and just using the argument "yeah but somebody _could_" isn't enough reason for me to go less anti-piracy. You have to consider that Re-Logic has been nice enough to let us public parts of the source code with our patches and essentially a 'tool' for modifying their game easily, let us do our part and respect their game.

This whole discussion has also never been about ways to circumvent the checks, that's all you guys have been going at because you are very "anti-DRM" and consider DRM to be a bad thing and want the checks removed. We are simply trying to defer people from pirating the game, but we obviously know that any dedicated pirate will always be able to pirate it. It isn't about that the checks are simple and easy to circumvent, but they are helping to stop 9/10 pirates if that makes sense. (And this is also primarily the reason why we want to stop discussing this matter now, since it's just giving pirates more/new ideas to pirate the game)
