### ISSUE TITLE
Main.MouseWorld from another player

### ISSUE THREAD

**Issue by wooden-utensil** [blushiemagic/tModLoader#512]
Using `Main.MouseWorld` sometimes _gets where the cursor is_ ___from another player___, if there are two players.
This is **very frustrating** when i'm trying to use
the item <sup>(which is calling `public override bool UseItem(Player player)`)</sup>.
Can you fix this problem.

> I click and hover over something, other player hovers over something, position is at where the other player is.

And also if you can: add a way of getting ***any*** *player*'s mouse position both relative to the world and the screen/GUI.
Thanks.

**Comment by wooden-utensil** [comment]
I don't want MouseScreen I want MouseWorld.

**Comment by JavidPack** [comment]
Can you post a minimum reproducible example mod showing this issue? To my knowledge, mouse positions are not synced at all so the issue might be something else. In any case, a complete mod that we can test would help.

**Comment by wooden-utensil** [comment]
Here is an example, just run it in a multiplayer server, just so you know I ran it in a tModLoader server _console window thingy_. I think smart cursor could be the problem? I've linked one without the auto-disable smart cursor, and one with, just to see if smart cursor makes a difference.

---

Disables Smart Cursor:

Source: [MouseMainWorldGlitchExample.zip](https://github.com/blushiemagic/tModLoader/files/3079991/MouseMainWorldGlitchExample.zip)

Build: [MouseMainWorldGlitchExample.zip](https://github.com/blushiemagic/tModLoader/files/3080004/MouseMainWorldGlitchExample.zip)

---

No Disabling Smart Cursor:

Source: [MouseMainWorldGlitchExampleNoDisableSmartCursor.zip](https://github.com/blushiemagic/tModLoader/files/3079992/MouseMainWorldGlitchExampleNoDisableSmartCursor.zip)

Build: [MouseMainWorldGlitchExampleNoDisableSmartCursor.zip](https://github.com/blushiemagic/tModLoader/files/3080006/MouseMainWorldGlitchExampleNoDisableSmartCursor.zip)

**Comment by JavidPack** [comment]
Haven't tested this yet, but I did notice you put code in UseItem that you did not gate with a if(player.whoAmI == Main.myPlayer)

UseItem is called on all clients, and things like your Explode method will run using Main.MouseWorld on all clients, even the clients not using the weapon. (This is how you can see other players doing a lot of the things)

If you use `if(player.whoAmI == Main.myPlayer)` around all the code, however, the other clients won't see the Dust or hear the sound. (The tile destruction should still sync I think.)

You also can't selectively call those lines of code using an if statement because the position in the Explode method will be different on all clients.

What vanilla code does usually is spawn a projectile, and the projectile takes care of exploding. The projectile spawn would sync properly. You can also just send a ModPacket containing a Vector2, then when clients receive it, Play the sound and spawn the dust.

In any case, using mouse position is hard because it is not synced in multiplayer, except incidentally through projectile spawns.


If you still need help, we can talk more, just thought I'd mention what the issue is since I noticed it.

**Comment by wooden-utensil** [comment]
> Haven't tested this yet, but I did notice you put code in UseItem that you did not gate with a if(player.whoAmI == Main.myPlayer)
> 
> UseItem is called on all clients, and things like your Explode method will run using Main.MouseWorld on all clients, even the clients not using the weapon. (This is how you can see other players doing a lot of the things)
> 
> If you use `if(player.whoAmI == Main.myPlayer)` around all the code, however, the other clients won't see the Dust or hear the sound. (The tile destruction should still sync I think.)
> 
> You also can't selectively call those lines of code using an if statement because the position in the Explode method will be different on all clients.
> 
> What vanilla code does usually is spawn a projectile, and the projectile takes care of exploding. The projectile spawn would sync properly. You can also just send a ModPacket containing a Vector2, then when clients receive it, Play the sound and spawn the dust.
> 
> In any case, using mouse position is hard because it is not synced in multiplayer, except incidentally through projectile spawns.
> 
> If you still need help, we can talk more, just thought I'd mention what the issue is since I noticed it.

Thank you so much! I'll remember next time: `if (player.whoAmI == Main.myPlayer)`.

**Comment by wooden-utensil** [comment]
Thanks I might try ModPacket!
