### ISSUE TITLE
Some characters in ModPack name crash

### ISSUE THREAD

**Issue by JavidPack** [blushiemagic/tModLoader#521]
Issue reported on Discord. The example was "Something <3"

Another report was "putting a backslash at the end of a modpack name crashes TmodLoader"

We need to sanitize the name since we use them as filenames

**Comment by wooden-utensil** [comment]
@JavidPack 

> We need to sanitize the name since we use them as filenames

Yes we definitely do. `\` will save to a folder! A player isn't a folder. `nul`/`con`/`prn`/`aux` etc will not save the player, because Windows can't have names of that, and when programs write to `nul` instead it does nothing. `\` `/` `:` `*` `?` `"` `<` `>` `|` are also invalid characters. Having `.` `..` `...` as the name will treat as the parent folder, which will store the players in the Terraria folder, [link here](https://www.youtube.com/watch?v=-Kvr_9ntpHg).

**Comment by Jofairden** [comment]
@wooden-utensil 
I added some validation in  8e8906d , I think it should be fixed now.
