### ISSUE TITLE
Issues while compiling CheatSheet for the first time.

### ISSUE THREAD

**Issue by MaxBarbet** [blushiemagic/tModLoader#555]
I can't compile CheatSheet mod cause i have errors syntax everywhere in code. I am asking myself if it's not a compiler problem.
I just downloaded the package, unzip it and moved it in Terraria>ModLoader>Mod Sources.
I have a syntax error only when the "=>" operator appear on the line.

There is the tModLoader error log
[Compile Errors.txt](https://github.com/blushiemagic/tModLoader/files/3293288/Compile.Errors.txt)

I am using Windows 8.1 and i am editing text with VScode if this could help.

I don't understand how to fix it, i am new in C# programming so thanks for helping me,
Max

**Comment by JavidPack** [comment]
The issue is that your folder paths are messed up, resulting in tmodloader not seeing the build.txt, resulting in tmodloader not seeing `languageVersion = 6` in build.txt. `languageVersion = 6` allows usage of the `=>` operator.

You'll need to rename and delete extra layers of folders so that `Terraria\ModLoader\Mod Sources\CheatSheet-0.5.0.2\CheatSheet-0.5.0.2\CheatSheetNPC.cs` is in `Terraria\ModLoader\Mod Sources\CheatSheet\CheatSheetNPC.cs`. Basically move everything up 1 folder and rename the folder to CheatSheet.

I can offer CheatSheet specific help on the cheat sheet discord: https://discord.gg/VzYmqu6

You can also come to the tmodloader discord: https://discord.gg/RMZCqq6

If your intention wasn't to develop cheat sheet, but just use Cheat Sheet, you just download the .tmod file instead of compiling the mod yourself.

**Comment by MaxBarbet** [comment]
I have other issues but thanks a lot for your help.
